baseurl = "https://inspiring-pike-52c512.netlify.com/"
languageCode = "en-us"
languageLang = "en"
title = "Kathy Smith | Photography"
theme = "beautifulhugo"

[Params]
  subtitle = "Build a beautiful and simple website in minutes"
  mainSections = ["post","posts"]
  logo = "android-chrome-144x144" # Expecting square dimensions
  favicon = "favicon.ico"
  dateFormat = "January 2, 2006"
  socialShare = false
  copyrightDate = "2020"
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"


[Author]
name = "Kathy Smith"
website = "https://kathysmith.photography/"
# facebook = "kathy.smith.33046"

[menu]
  [[menu.main]]
      identifier = "action"
      name = "Action"
      url = "/tags/action"
      weight = 1

  [[menu.main]]
      parent = "action"
      name = "Sports"
      url = "/tags/sports"
      weight = 1

  [[menu.main]]
      parent = "action"
      name = "Events"
      url = "/tags/events"
      weight = 2

  [[menu.main]]
      parent = "action"
      name = "Motion"
      url = "/tags/motion"
      weight = 3

  [[menu.main]]
      identifier = "people"
      name = "People"
      weight = 1

  [[menu.main]]
      parent = "people"
      name = "Black and White"
      url = "/tags/bw"
      weight = 1

  [[menu.main]]
      name = "Scapes"
      url = "tags/scapes"
      weight = 1

  [[menu.main]]
      name = "Stills"
      url = "tags/stills"
      weight = 1

  [[menu.main]]
      name = "Wild"
      url = "tags/wild"
      weight = 1

  [[menu.wild]]
      name = "Wild"
      url = "/tags/wild"
      weight = 1

  [[menu.wild]]
      parent = "wild"
      name = "Birds"
      url = "/tags/birds"
      weight = 1