baseurl = "https://inspiring-pike-52c512.netlify.com/"
languageCode = "en-us"
languageLang = "en"
title = "Kathy Smith | Photography"
theme = "beautifulhugo"

[author]
name = "Kathy Smith"
website = "https://kathysmith.photography/"